### ISSUE TITLE
Fetching Points within coordinates received from Google Maps

### ISSUE THREAD

**Issue by GTCrais** [MatanYadaev/laravel-eloquent-spatial#119]
Hi, this is not an issue, I just need help with something, if that's alright.

I pull google map bounds, and the result I get is this:

```
{ south: 44.85856815478515, west: 12.956013352988899, north: 46.61810356385327, east: 18.40797868502015 }
```

or this:

North-east:
```
{ lat: 46.61810356385327, lng: 18.40797868502015}
```

South-west:
```
{ lat: 44.85856815478515, lng: 12.956013352988899 }
```

What I'm trying to do is fetch Locations form my MySQL database within those bounds. I've figured I probably need to use `whereWithin()` method, which accepts `Geometry` as the second argument. How do I make an instance of `Geometry` with the data that I have?

Is it as simple as just translating those point to south-east and north-west, and then creating a `Polygon` using `fromJson`, or is there more to it?

Thanks!

**Comment by MatanYadaev** [comment]
You need to make a polygon with 5 points and pass it to the method
1. North-east
2. North-west
3. South-west
4. South-east
5. North-east

**Comment by GTCrais** [comment]
Thanks, that seems to have worked!

**Comment by GTCrais** [comment]
Final code, might help someone some day:
```php
$validated = $request->validate([
	'mapBounds' => ''
]);

$data = [
	'type' => 'Polygon',
	'coordinates' => [
		[
			[$validated['mapBounds']['west'], $validated['mapBounds']['north']],
			[$validated['mapBounds']['west'], $validated['mapBounds']['south']],
			[$validated['mapBounds']['east'], $validated['mapBounds']['south']],
			[$validated['mapBounds']['east'], $validated['mapBounds']['north']],
			[$validated['mapBounds']['west'], $validated['mapBounds']['north']]
		]
	]
];

$locations = MyLocationModel::whereWithin('location', Polygon::fromJson(json_encode($data), Srid::WGS84->value))->get();
```
