### ISSUE TITLE
Help required using Point with PostgeSQL

### ISSUE THREAD

**Issue by AlexGodbehere** [MatanYadaev/laravel-eloquent-spatial#120]
I'm in the process of migrating my database from MySQL to PostgreSQL.

A few of my models cast their location field to `Point`, which is now throwing an error.

```php
protected $casts = [
    'location' => Point::class,
];
```

```bash
# AxisOrder.php on line 20
TypeError: MatanYadaev\EloquentSpatial\AxisOrder::isMariaDb(): Argument #1 ($connection) must be of type Illuminate\Database\MySqlConnection, Illuminate\Database\PostgresConnection given
```

The readme of this package states compatability with `Postgres 12/13/14/15/16 with PostGIS 3.4`. What am I missing?

**Comment by MatanYadaev** [comment]
Hi @AlexGodbehere, try to upgrade to v4
