### ISSUE TITLE
InvalidArgumentException after 4.3.0 upgrade

### ISSUE THREAD

**Issue by towel** [MatanYadaev/laravel-eloquent-spatial#126]
Hi, without having a lot of time to dig into it right now, I want to make you aware that since upgrading to 4.3.0 my application errors and I had to downgrade to 4.2.0 for now. Not sure yet if this is a regression from #125 or if I've been using something fundamentally wrong from the beginning.

 ![Error screenshot](https://github.com/user-attachments/assets/6ee911e3-576e-42e2-96c8-dfb9156a97dd)

Any pointers to assist in tracking this down are much appreciated.

**Comment by MatanYadaev** [comment]
Can you share some context about the `area` column? From the screenshot it seems like a generic geometry, not a specific spatial type, isn't it?

**Comment by towel** [comment]
Hi, thanks for getting back tom e so quickly.
Yes, `area` is a `Geometry::class` and populates from Openstreetmap / Nominatim geoJson data
`'area' => Geometry::fromArray((array) $city_geoinfo['geojson'])`. 
The area is then used to display city areas on a Leaflet slippy map.

**Comment by MatanYadaev** [comment]
This scenario wasn't covered with tests. Fixed in v4.3.1 and added tests
