### ISSUE TITLE
Object of class Shapefile\Geometry\MultiPolygon could not be converted to string when using `update()

### ISSUE THREAD

**Issue by Paxton0222** [MatanYadaev/laravel-eloquent-spatial#129]
**Laravel version**: 11.20.0
**PHP version**: 8.3
**laravel-eloquent-spatial version**: 4.3.2

### Problem Description:

When trying to update a `MultiPolygon` geometry using the `update()` method in Eloquent, I encounter the following error:

```
Object of class Shapefile\Geometry\MultiPolygon could not be converted to string
```

### Query Example:

Here’s the query I am using:

```php
County::where('geometry', '=', null)
    ->update([
        'geometry' => new MultiPolygon([
            new Polygon([
                new Linestring([
                    new Point(0, 0),
                    new Point(0, 1),
                    new Point(1, 1),
                    new Point(1, 0),
                    new Point(0, 0),
                ]),
            ]),
        ]),
    ]);
```

### Model Setup:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use MatanYadaev\EloquentSpatial\Traits\HasSpatial;
use Shapefile\Geometry\MultiPolygon;
use Shapefile\Geometry\Polygon;

class County extends Model
{
    use HasSpatial;

    public $timestamps = false;

    protected $table = 'county';

    protected $guarded = ['id'];

    protected $fillable = [
        'name',
        'bbox',
        'geometry',
    ];

    protected $casts = [
        'name' => 'string',
        'bbox' => Polygon::class,
        'geometry' => MultiPolygon::class,
    ];
}
```

### Steps to Reproduce:

1. Create a `MultiPolygon` object.
2. Use the `update()` method to try and update the `geometry` field in the database.

### Expected Behavior:

The `geometry` field should be updated with the `MultiPolygon` value.

### Actual Behavior:

I get an error that the `MultiPolygon` object cannot be converted to a string.

### Question:

Does `laravel-eloquent-spatial` support updating geometry fields using the `update()` method directly? Or is there a specific configuration or method that needs to be used?

**Comment by MatanYadaev** [comment]
Hi @Paxton0222, I think it doesn't work because you run `->update` in the Query Builder and not in Eloquent, which passes the casting logic, and therefore, it doesn't convert the `MultiPolygon` instance into WKT format.
You can fix it by first fetching the record and then update it: `Country::where(...)->first()->update(...)`

**Comment by Paxton0222** [comment]
@MatanYadaev Thank you so much for clearing up my confusion!
