### ISSUE TITLE
Extends Geometry does't work with fromArray() 

### ISSUE THREAD

**Issue by Mohammed-Alama** [MatanYadaev/laravel-eloquent-spatial#130]
I have been using #125 to extends Polygon class
and I have in issue with create polygons , the main reason to override this classes is to has different SRID other than `0`
and when i tried to override fromArray() it's does not working

I think we need to have SRID configurable instead of using it as static value
and also determine how to prioritize it 
@MatanYadaev please advice

![CleanShot 2024-11-23 at 18 38 35](https://github.com/user-attachments/assets/1bcd93a1-b478-4cff-97d3-da40df846ea6)

**Comment by MatanYadaev** [comment]
I believe this fix should help you. Let me know if it didn't. https://github.com/MatanYadaev/laravel-eloquent-spatial?tab=readme-ov-file#set-default-srid
