### ISSUE TITLE
Support for MySQL 8 SRID?

### ISSUE THREAD

**Issue by sikhlana** [MatanYadaev/laravel-eloquent-spatial#27]
I have been using https://github.com/grimzy/laravel-mysql-spatial/ which has support for SRIDs. I am planning to migrate to this package as it has greater potential with Laravel's current ecosystem.

But looking at the source code, I don't see any support for SRID which will conflict with my current database schema. Is there any plan or are you interested in a PR?

**Comment by MatanYadaev** [comment]
Hi @sikhlana! I have no experience with SRID and I never needed it, so I didn't implement support for SRID.

I will be very happy if you could send a PR. Just make sure it has a good testing coverage.

Thanks so much.

**Comment by MatanYadaev** [comment]
@sikhlana There's something I can help with in order to push this task forward?

**Comment by MatanYadaev** [comment]
@sikhlana I closed the issue. If the issue is still relevant to someone, please contact me or just submit a PR.

**Comment by sikhlana** [comment]
@MatanYadaev apologies for the late reply. I have been busy with a high priority project so not getting the time to add support for SRIDs. Will be able to come up with something within a few days.

**Comment by Gemui** [comment]
I created pull request for SRID support #42

**Comment by MatanYadaev** [comment]
@sikhlana Implemented in v2.1
