### ISSUE TITLE
Reverse point order

### ISSUE THREAD

**Issue by janisgitendorfs** [MatanYadaev/laravel-eloquent-spatial#31]
Hello,

![image](https://user-images.githubusercontent.com/1249446/161321296-b6055712-1134-414e-b174-30ffcac22203.png)

The constructor accepts LAT as the first parameter and LNG as the second but the toArray() order and saving in the database are reversed.  Is there any plans to change this or at least have a "reverse" functionality since in google maps for example the order is "LAT LNG".

**Comment by MatanYadaev** [comment]
@janisgitendorfs The serialization methods (`toArray`, `toJson`, etc) return a geometry object formatted in the GeoJSON schema. I can understand the confusion, but I am not sure it should be changed.

**Comment by joni1993** [comment]
During some testing i noticed there is in fact a mistake currently, i noticed it when i tried to save a point generated with `new Point($this->faker->latitude(), $this->faker->longitude(), 4326)`, when mysql claimed `Latitude -165.142622 is out of range in function st_geomfromtext. It must be within [-90.000000, 90.000000]`. So there is definitely a mixup between latitude and longitude.
According to https://dev.mysql.com/blog-archive/axis-order-in-spatial-reference-systems/ the order of axis can be different depending on the SRID.
As suggested in the post we can workaround this by specifing "axis-order=long-lat" to the ST_GeomFromText function.

**Comment by MatanYadaev** [comment]
@joni1993 You are right, I fixed it in the last version. Please check and update me.

**Comment by joni1993** [comment]
Ugh, sorry for bothering you - Had just encountered this problem like 3 days ago and did not see the update.

All good! Thank you!
