### ISSUE TITLE
Nullable geospatial fields, default values

### ISSUE THREAD

**Issue by Synchro** [MatanYadaev/laravel-eloquent-spatial#32]
In your code example you use this in the migration:

```php
$table->point('location')->nullable();
```
However, if you try to do that and want to search on this field (i.e. it has a spatial index), this will cause an error:

> All parts of a SPATIAL index must be NOT NULL

So spatial fields cannot be null at all, which means they must also be initialised to non-null values in a constructor, as that can't be done in the `attributes` array, and can't handled by a cast.

But then I run into another issue. If my `Location` model has:

```php
public function newEloquentBuilder($query): SpatialBuilder
{
    return new SpatialBuilder($query);
}

protected $casts = [
    'location' => \MatanYadaev\EloquentSpatial\Objects\Point::class,
];

public function __construct()
{
    $this->location = new \MatanYadaev\EloquentSpatial\Objects\Point(51.5032973, -0.1195537);
}
```
and I do this:

```php
    $location = new Location();
    $location->save();
```

it fails with:

>TypeError: MatanYadaev\EloquentSpatial\Objects\Geometry::fromWkb(): Argument #1 ($wkb) must be of type string, Illuminate\Database\Query\Expression given, called in vendor/matanyadaev/laravel-eloquent-spatial/src/GeometryCast.php on line 39

How should this be done?

**Comment by MatanYadaev** [comment]
Hi @Synchro! First, your `location` spatial column can't be nullable because you added a spatial index to this column. MySQL requires spatial indexed columns to be not nullable, it's not related to the package.
Second, I wasn't able to reproduce the bug. I wrote the same code and it worked just fine.
Can you please reproduce the issue in a new repo so I could debug it? Or just fork this repo and add a failed test?

**Comment by Synchro** [comment]
I know that about the spatial indexes – it would be good to mention that in the docs though, because a lack of a spatial index means that most of the spatial search functions won't work efficiently, which seems a shame when that's most of the point of having them!

I have managed to solve my issue – I think it was because I was converting from `Grimzy\LaravelMysqlSpatial` and there were still some pieces of it left enabled in my model. Thanks for your library though – I've already had more success with it than that one!
