### ISSUE TITLE
response()->json() fails as it incorrectly interprets spatial fields

### ISSUE THREAD

**Issue by lukepower** [MatanYadaev/laravel-eloquent-spatial#34]
When returning a collection with some spatial fields in it (in our case, all Point's) like this:

return response()->json($res);

We get a 500 error on the server with "Malformed UTF-8 characters, possibly incorrectly encoded".
As soon as I null the spatial field in the DB, the error dissolves. It seemingly is unable to correctly create a json out of the field.
Using latest Laravel 9 and current master.

**Comment by MatanYadaev** [comment]
@lukepower Can you please help me to reproduce the issue by forking this repo and creating a PR with a failing test? Or provide a link to a new Laravel repo that has this issue?

**Comment by lukepower** [comment]
@MatanYadaev Just came back from vacation, will do it asap.
Just a quick note, it seems that when I access the spatial field I get the binary data, i.e. like this:

b1E� ���%ǝ��?

I guess something is wrong with the way I set up the whole package...

**Comment by Synchro** [comment]
That's the same bug as in #28, which I've still been unable to solve.

**Comment by mostafaznv** [comment]
This issue happens when someone wants to see changes of a record (`getChanges`, `isDirty` and ...).

For example, In Nova 4 there is a feature to log all changes of model's records. 
when it wants to log **changed** and **original** values in database, this error happens.

**Comment by devinfd** [comment]
Just FYI I'm using v2.2 and still getting a `Unable to JSON encode payload. Error code: 5`

**Comment by MatanYadaev** [comment]
Hi @devinfd, please respect my time, if you want me to fix the issue, make it easy to me to reproduce it. It will be best if you'll create a fork of this repo with a failing test, or a Laravel app repo that has a broken endpoint.
I wasn't able to reproduce the issue.

**Comment by devinfd** [comment]
Of course @MatanYadaev. I'm am currently debugging my issue to make sure that it's an issue on my end. I made the above comment because in your previous comment you said "Please check it." So I thought you would want the feedback. 

Awesome package! Glad to see that it's well cared for.
