### ISSUE TITLE
Updating location data using update/updateOrCreate doesnt work

### ISSUE THREAD

**Issue by Subwaytime** [MatanYadaev/laravel-eloquent-spatial#40]
Hey there,

so i am currently working on a Project that needs Points for a Location and we are sending over the Data as an array.
Right now i am trying to get a helper function to work, but it seems it only works with `create()` and everything else like `update()`, `updateOrCreate()`, doesnt seem to work at all.

```php
    /**
     * Create or update event location
     * Converts latitude/longitude to SpatialPoint.
     */
    public function setLocation(array $data): void
    {
        $location = Arr::map($data, function ($value, $key) {
            if (str_contains($key, 'coordinates')) {
                $value = new Point($value['latitude'], $value['longitude']);
            }

            return $value;
        });

        $this->location()->updateOrCreate($location);
    }
```

Error that i am getting back is (note this is from postman):
`"Object of class MatanYadaev\\EloquentSpatial\\Objects\\Point could not be converted to string"`

For the setup
location is just casting two attributes (exact_coordinates and fuzzy_coordinates, which are always given from the post request) into a `Point::class`.

Edit: Using laravel-eloquent-spatial 2.0

**Comment by Subwaytime** [comment]
Hey there, sorry for the late response!
I will get to the reproduction probably next weekend, as i am super busy right now..

**Comment by MatanYadaev** [comment]
@Subwaytime No problem, for now I close this issue. Please create a new issue with a failing test whenever you're ready.
