### ISSUE TITLE
Database connection [mysql] not configured

### ISSUE THREAD

**Issue by nouman-ashraf-awan** [MatanYadaev/laravel-eloquent-spatial#68]
I have my database.php file looks like this and there is no default connection defined. Its giving me error on composer install.
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/80042136/197547414-b9722fcc-a215-4b58-ac2d-7bdc91a6d2dd.png">
@MatanYadaev Can you please resolve this?

**Comment by MatanYadaev** [comment]
@nouman-ashraf-awan I see, I guess it's because of this line: https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/c998cc091996d149a6f17f88e1e236ba55859694/src/EloquentSpatialServiceProvider.php#L23

I need to see what should I do in case there is no default connection. Any suggestion?

**Comment by MatanYadaev** [comment]
BTW @nouman-ashraf-awan, why don't you have a default connection? https://github.com/laravel/laravel/blob/9.x/config/database.php#L18

**Comment by nouman-ashraf-awan** [comment]
@MatanYadaev I forgot to mention i have this line already in database.php. But its still giving me error.
Line=> 'default' => env('DB_CONNECTION', 'mysql'),

**Comment by nouman-ashraf-awan** [comment]
@MatanYadaev I forgot to mention i have this line already in database.php. But it's still giving me error.
'default' => env('DB_CONNECTION', 'mysql'),

**Comment by nouman-ashraf-awan** [comment]
> @nouman-ashraf-awan I see, I guess it's because of this line:
> 
> https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/c998cc091996d149a6f17f88e1e236ba55859694/src/EloquentSpatialServiceProvider.php#L23
> 
> I need to see what should I do in case there is no default connection. Any suggestion?

May be you can follow this https://github.com/grimzy/laravel-mysql-spatial/blob/master/src/SpatialServiceProvider.php

**Comment by nouman-ashraf-awan** [comment]
@MatanYadaev Now facing `SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field` while adding Polygon for a location.
followed [this](https://github.com/MatanYadaev/laravel-eloquent-spatial) pattern
`update `location` set `polygon` = POLYGON((55.124425899895 25.071458205224, 55.127732 25.068963, 55.129105 25.067884, 55.129824 25.067417, 55.130671 25.067048, 55.131326 25.066756, 55.132377 25.066523, 55.132967 25.066203, 55.13507 25.068253, 55.136894 25.070304, 55.138675 25.072218, 55.140156 25.073812, 55.142097 25.076057, 55.143492 25.077378, 55.144179 25.077913, 55.147054 25.08041, 55.150841 25.083587, 55.152472 25.084987, 55.153331 25.085754, 55.154039 25.086328, 55.154028 25.086648, 55.153899 25.08726, 55.152698 25.088377, 55.151743 25.089379, 55.150681 25.090185, 55.148642 25.09173, 55.150423 25.09378, 55.151088 25.094538, 55.152225 25.095626, 55.1542 25.097608, 55.15584793951 25.099253479479, 55.152843722599 25.101711200566, 55.152821303316 25.101341947461, 55.152647192115 25.100739355849, 55.151943650842 25.099522106307, 55.149551550382 25.096715552657, 55.148045469999 25.095019947921, 55.147822038009 25.094903670661, 55.146863413833 25.093807211541, 55.14647939492 25.093352666531, 55.145384209571 25.092595510635, 55.14524899639 25.092532170503, 55.145087619202 25.092489054535, 55.144823544682 25.092466492384, 55.146409128121 25.091247147176, 55.146559869988 25.091298505704, 55.146709583538 25.091244616504, 55.147825751074 25.090437886168, 55.14723923671 25.089835391734, 55.145539051264 25.087957129345, 55.144128176903 25.08758321608, 55.143879750696 25.087435773766, 55.143585650868 25.087183735053, 55.14337305757 25.087027584275, 55.143028711743 25.087306743937, 55.141110409971 25.08881451259, 55.14033887511 25.089416863541, 55.139709591331 25.089925458623, 55.139650342736 25.089959733506, 55.139520271223 25.090062350595, 55.13942415925 25.090143244628, 55.139491458063 25.090202996998, 55.139493172192 25.090213540898, 55.139484030391 25.090221618451, 55.139472929678 25.090226389604, 55.139399390673 25.090160598282, 55.139042674358 25.090443170684, 55.138565077492 25.090823990774, 55.138357063059 25.090991196678, 55.138362270001 25.091025279908, 55.138291918212 25.091090520588, 55.138451662938 25.091259036902, 55.138467473461 25.091242051816, 55.138537862028 25.091313409234, 55.138510646563 25.091333242029, 55.138575748829 25.091399239546, 55.138554113896 25.091417129898, 55.138572225941 25.091438281844, 55.138598758151 25.091430847818, 55.138651822572 25.091486198068, 55.138635187589 25.091512051626, 55.138714989568 25.091598867983, 55.138629065881 25.091670099349, 55.13855172917 25.091597166618, 55.138522851864 25.091600303533, 55.138445713487 25.091515878937, 55.138402893366 25.091543055461, 55.138364591774 25.091498506673, 55.138302807226 25.091524596171, 55.138070097597 25.091280251856, 55.137939895687 25.09139167046, 55.137967934702 25.091466245646, 55.137871995564 25.091530674955, 55.137824338702 25.091518331958, 55.137729024977 25.091571306781, 55.137427195808 25.091766643225, 55.137088572302 25.091869906975, 55.136694501578 25.092008453487, 55.136363724661 25.092104364503, 55.13585960063 25.092132591103, 55.1355694766 25.092159817861, 55.135151723609 25.09219029965, 55.134794782372 25.092159817861, 55.134437 25.092091672139, 55.134161188248 25.091964190228, 55.133965 25.091685635142, 55.133721794334 25.091152823881, 55.133697247009 25.090968262205, 55.129182567805 25.088969086276, 55.129427191263 25.088463556132, 55.133998517759 25.090462443794, 55.13407404748 25.090152547232, 55.133961742392 25.089907561951, 55.133793567471 25.089741289882, 55.133701770409 25.089528003466, 55.133815054699 25.089455394184, 55.13413422228 25.089163487582, 55.134472517717 25.08893235005, 55.134952059348 25.088765670613, 55.135220047792 25.088716404685, 55.135657342009 25.088667138756, 55.136010936803 25.088838643859, 55.136472687732 25.089061088864, 55.136782504249 25.088752569215, 55.136940928306 25.088032722584, 55.136872104489 25.087265580158, 55.13672758444 25.086852639782, 55.136564704727 25.086300981813, 55.136497 25.086065, 55.138128 25.084899, 55.14037 25.083267, 55.140681 25.082971, 55.141196 25.082548, 55.141263 25.082311, 55.140378 25.081137, 55.140156 25.080682, 55.139662 25.080381, 55.138954 25.079973, 55.138181 25.079545, 55.13757 25.079088, 55.13698 25.078447, 55.136636 25.077757, 55.136497 25.077213, 55.136079 25.076513, 55.135649 25.076154, 55.135263 25.075998, 55.134662 25.075823, 55.134341 25.075746, 55.134083 25.075707, 55.133622 25.075503, 55.132978 25.075065, 55.132656 25.074599, 55.132474 25.074113, 55.132366 25.073598, 55.132302 25.07319, 55.132152 25.07283, 55.131959 25.072548, 55.131508 25.072199, 55.13109 25.071936, 55.130639 25.071742, 55.130124 25.071606, 55.129749 25.071586, 55.129362 25.071625, 55.129019 25.071684, 55.128697 25.071713, 55.128407 25.071664, 55.128064 25.071528, 55.127878461267 25.071404176277, 55.127598863771 25.07153594216, 55.127274177843 25.071182222445, 55.127055399622 25.071047959352, 55.126917792884 25.070622999528, 55.12644453684 25.070810944069, 55.124928709658 25.071918756217, 55.124425899895 25.071458205224)), `point` = ST_GeomFromText('POINT(55.142398834229 25.078399658203)', 0, 'axis-order=long-lat') where `id` = 5003)`

**Comment by nouman-ashraf-awan** [comment]
> @MatanYadaev @devinfd Now facing `SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field` while adding Polygon for a location. followed [this](https://github.com/MatanYadaev/laravel-eloquent-spatial) pattern `update `location`set`polygon`= POLYGON((55.124425899895 25.071458205224, 55.127732 25.068963, 55.129105 25.067884, 55.129824 25.067417, 55.130671 25.067048, 55.131326 25.066756, 55.132377 25.066523, 55.132967 25.066203, 55.13507 25.068253, 55.136894 25.070304, 55.138675 25.072218, 55.140156 25.073812, 55.142097 25.076057, 55.143492 25.077378, 55.144179 25.077913, 55.147054 25.08041, 55.150841 25.083587, 55.152472 25.084987, 55.153331 25.085754, 55.154039 25.086328, 55.154028 25.086648, 55.153899 25.08726, 55.152698 25.088377, 55.151743 25.089379, 55.150681 25.090185, 55.148642 25.09173, 55.150423 25.09378, 55.151088 25.094538, 55.152225 25.095626, 55.1542 25.097608, 55.15584793951 25.099253479479, 55.152843722599 25.101711200566, 55.152821303316 25.101341947461, 55.152647192115 25.100739355849, 55.151943650842 25.099522106307, 55.149551550382 25.096715552657, 55.148045469999 25.095019947921, 55.147822038009 25.094903670661, 55.146863413833 25.093807211541, 55.14647939492 25.093352666531, 55.145384209571 25.092595510635, 55.14524899639 25.092532170503, 55.145087619202 25.092489054535, 55.144823544682 25.092466492384, 55.146409128121 25.091247147176, 55.146559869988 25.091298505704, 55.146709583538 25.091244616504, 55.147825751074 25.090437886168, 55.14723923671 25.089835391734, 55.145539051264 25.087957129345, 55.144128176903 25.08758321608, 55.143879750696 25.087435773766, 55.143585650868 25.087183735053, 55.14337305757 25.087027584275, 55.143028711743 25.087306743937, 55.141110409971 25.08881451259, 55.14033887511 25.089416863541, 55.139709591331 25.089925458623, 55.139650342736 25.089959733506, 55.139520271223 25.090062350595, 55.13942415925 25.090143244628, 55.139491458063 25.090202996998, 55.139493172192 25.090213540898, 55.139484030391 25.090221618451, 55.139472929678 25.090226389604, 55.139399390673 25.090160598282, 55.139042674358 25.090443170684, 55.138565077492 25.090823990774, 55.138357063059 25.090991196678, 55.138362270001 25.091025279908, 55.138291918212 25.091090520588, 55.138451662938 25.091259036902, 55.138467473461 25.091242051816, 55.138537862028 25.091313409234, 55.138510646563 25.091333242029, 55.138575748829 25.091399239546, 55.138554113896 25.091417129898, 55.138572225941 25.091438281844, 55.138598758151 25.091430847818, 55.138651822572 25.091486198068, 55.138635187589 25.091512051626, 55.138714989568 25.091598867983, 55.138629065881 25.091670099349, 55.13855172917 25.091597166618, 55.138522851864 25.091600303533, 55.138445713487 25.091515878937, 55.138402893366 25.091543055461, 55.138364591774 25.091498506673, 55.138302807226 25.091524596171, 55.138070097597 25.091280251856, 55.137939895687 25.09139167046, 55.137967934702 25.091466245646, 55.137871995564 25.091530674955, 55.137824338702 25.091518331958, 55.137729024977 25.091571306781, 55.137427195808 25.091766643225, 55.137088572302 25.091869906975, 55.136694501578 25.092008453487, 55.136363724661 25.092104364503, 55.13585960063 25.092132591103, 55.1355694766 25.092159817861, 55.135151723609 25.09219029965, 55.134794782372 25.092159817861, 55.134437 25.092091672139, 55.134161188248 25.091964190228, 55.133965 25.091685635142, 55.133721794334 25.091152823881, 55.133697247009 25.090968262205, 55.129182567805 25.088969086276, 55.129427191263 25.088463556132, 55.133998517759 25.090462443794, 55.13407404748 25.090152547232, 55.133961742392 25.089907561951, 55.133793567471 25.089741289882, 55.133701770409 25.089528003466, 55.133815054699 25.089455394184, 55.13413422228 25.089163487582, 55.134472517717 25.08893235005, 55.134952059348 25.088765670613, 55.135220047792 25.088716404685, 55.135657342009 25.088667138756, 55.136010936803 25.088838643859, 55.136472687732 25.089061088864, 55.136782504249 25.088752569215, 55.136940928306 25.088032722584, 55.136872104489 25.087265580158, 55.13672758444 25.086852639782, 55.136564704727 25.086300981813, 55.136497 25.086065, 55.138128 25.084899, 55.14037 25.083267, 55.140681 25.082971, 55.141196 25.082548, 55.141263 25.082311, 55.140378 25.081137, 55.140156 25.080682, 55.139662 25.080381, 55.138954 25.079973, 55.138181 25.079545, 55.13757 25.079088, 55.13698 25.078447, 55.136636 25.077757, 55.136497 25.077213, 55.136079 25.076513, 55.135649 25.076154, 55.135263 25.075998, 55.134662 25.075823, 55.134341 25.075746, 55.134083 25.075707, 55.133622 25.075503, 55.132978 25.075065, 55.132656 25.074599, 55.132474 25.074113, 55.132366 25.073598, 55.132302 25.07319, 55.132152 25.07283, 55.131959 25.072548, 55.131508 25.072199, 55.13109 25.071936, 55.130639 25.071742, 55.130124 25.071606, 55.129749 25.071586, 55.129362 25.071625, 55.129019 25.071684, 55.128697 25.071713, 55.128407 25.071664, 55.128064 25.071528, 55.127878461267 25.071404176277, 55.127598863771 25.07153594216, 55.127274177843 25.071182222445, 55.127055399622 25.071047959352, 55.126917792884 25.070622999528, 55.12644453684 25.070810944069, 55.124928709658 25.071918756217, 55.124425899895 25.071458205224)),`point`= ST_GeomFromText('POINT(55.142398834229 25.078399658203)', 0, 'axis-order=long-lat') where`id` = 5003)`

@MatanYadaev  @devinfd  @dzhwar-k  Issue is occuring due to missing ST_GeomFromText() before POLYGON like POINT ST_GeomFromText('POINT(55.142398834229 25.078399658203)'

**Comment by MatanYadaev** [comment]
@nouman-ashraf-awan I'm not sure I'm following. There is a bug? How can I help?

**Comment by nouman-ashraf-awan** [comment]
> @nouman-ashraf-awan I'm not sure I'm following. There is a bug? How can I help?

@MatanYadaev  It is automatically adding ST_GeomFromText before Point but not adding before Polygon.Therefor giving error. I have compared this query with grizmy package query. That is the only thing missing in query.

**Comment by MatanYadaev** [comment]
@nouman-ashraf-awan Can you please fork this repository and add a failing test that demonstrates this issue?
