### ISSUE TITLE
Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field

### ISSUE THREAD

**Issue by Synchro** [MatanYadaev/laravel-eloquent-spatial#69]
I'm getting a casting problem when running this update:

I have a `Point` value set from request properties like this:

    $return_location = new Point((float)$request->latitude, (float)$request->longitude);

This is then used to update DB records:

                $count = Checkout::query()
                    ->where('user_id', $user->id)
                    ->limit(1)
                    ->update(
                        [
                            'return_location'   => $return_location,
                        ]
                    );

but even though the Point object is valid, and has a cast set correctly in its model, it fails like this:

```
SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY
field (SQL: update `checkouts` set `return_location` = POINT(-0.118092 51.509865), `checkouts`.`updated_at` = 
2022-12-06 11:03:38 where `user_id` = 4 limit 1)
```

In other contexts this field works fine.

Is there some limitation I'm running into here, or a bug?

**Comment by Synchro** [comment]
Ah, ok, that explains it. I will have to take the long way around!

**Comment by Synchro** [comment]
One thought – while casts might not be applied _automatically_, what should I do to make use of the casting _manually_? For example:

```php
$count = Checkout::query()
                ->where('user_id', $user->id)
                ->limit(1)
                ->update(
                    [
                        'return_location'   => DB::raw((string)$return_location),
                    ]
                );
```

My only concern here is that the default string representation might not be one that's compatible with what the DB is expecting. Is this the right way to do it, or do I need to call some `toWkt()` method or similar?

**Comment by MatanYadaev** [comment]
There is no clean way to do that today.

The logic happens here: https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/de5a041f38b06f4ce7687c31a08d55741268b425/src/GeometryCast.php#L59

This code should work, although I didn't test it:
```php
$geometryCast = new GeometryCast(Point::class);
$model = new Checkout(); // just to get the DB connection out of it
$wkt = $geometryCast($model, '', $return_location, []);
```

If you want, you can submit a PR that makes it less dirty. It should be a function that receives a DB connection and a `Geometry` instance and returns a WKT that can be inserted into the DB.
