### ISSUE TITLE
"Expected MatanYadaev\EloquentSpatial\GeometryCast, string given" while swapping two records

### ISSUE THREAD

**Issue by RahulKRaj7** [MatanYadaev/laravel-eloquent-spatial#79]
Hi!,
i am trying to implement draft functionality on model. in that while trying to swap two records. i am facing `Expected MatanYadaev\EloquentSpatial\GeometryCast, string given `this type of error.
Updating location data doesn't work.
Below is the snapshot of swapping code.
```
$oldAttributes = $published?->getAttributes() ?? [];
        $newAttributes = $this->getAttributes();
        Arr::forget($oldAttributes, $this->getKeyName());
        Arr::forget($newAttributes, $this->getKeyName());

        $published->forceFill($newAttributes);
        $this->forceFill($oldAttributes);
```

The field is casted in model as
`location' => Point::class,`

in the migration the field is created as
`$table->point('location')->nullable();`

Using [Laravel-Drafts](https://github.com/oddvalue/laravel-drafts) package for implementing draft functionality.

**Comment by MatanYadaev** [comment]
Hi @RahulKRaj7, can you share with me a wider context? Ideally, if you could fork this repo and add a failing test, it will help me to understand the issue better.

I reproduced this error with a slightly different error message: `InvalidArgumentException : Expected MatanYadaev\EloquentSpatial\GeometryCast, Illuminate\Database\Query\Expression given.`

So I would like to understand how to reproduce your case.

**Comment by RahulKRaj7** [comment]
Thanks for your reply and for your work on this library. but sorry i didn't get time to fork this repo and add and test the failing test. Here's a failing test, which I thought would pass:

```php
it('throws exception when swapping geometry field in two records using getAttributes()', function (): void
{
	expect(function (): void {
		$point = new Point(0, 180);
		$point2 = new Point(0, 0);
		$testPlace = TestPlace::factory()->make([
			'point' => $point,
		]);
		$testPlace2 = TestPlace::factory()->make([
			'point' => $point2,
		]);
		$oldAttributes = $testPlace->getAttributes();
		$newAttributes = $testPlace2->getAttributes();
		
		Arr::forget($oldAttributes, $testPlace->getKeyName());
		Arr::forget($newAttributes, $testPlace->getKeyName());
		
		$testPlace->forceFill($newAttributes);
		$testPlace2->forceFill($oldAttributes);
	})->toThrow(InvalidArgumentException::class);
});
```

**Comment by MatanYadaev** [comment]
@RahulKRaj7 Fixed, thanks for the help.

**Comment by hiteshsamcom** [comment]
@MatanYadaev faces this issue in the `v.2.10` branch so can you please update it?
