### ISSUE TITLE
Polygon SRID

### ISSUE THREAD

**Issue by Krato** [MatanYadaev/laravel-eloquent-spatial#82]
Hi everyone!

We're facing some problems when storing a polygon with a srid. The problem is that is saving without the srid, so is failing when comparing with other models with srid working.

Example:

```php
$data = "POLYGON((17.03558877746583 -22.543548588275577,17.046918428344735 -22.5888848509733,17.08279565612794 -22.577235171974756,17.122792756958017 -22.572559173452948,17.09824518005372 -22.5226191338314,17.06502870361329 -22.528803166402827,17.03558877746583 -22.543548588275577))";

$polygon = Polygon::fromWkt($data, 4326);
```

When polygon is stored on DB, srid is not saving.

Can you check it please?

**Comment by MatanYadaev** [comment]
@Krato Can you please fork the repo and push a commit with a failing test? I'll make sure to fix the test.

**Comment by Krato** [comment]
@MatanYadaev Yes, the problem is when the model is updated, not on creation. Let me check if I can create a test

**Comment by MatanYadaev** [comment]
@Krato I see the issue but I don't have a good answer.
The `Geometry@toArray` function returns a GeoJSON array, which doesn't contain SRID, and then when you use `Geometry@fromArray`, you create a geometry instance without SRID.

```php
it('test', function (): void {
  $polygon = Polygon::fromWkt(
    wkt: "POLYGON((17.03558877746583 -22.543548588275577,17.046918428344735 -22.5888848509733,17.08279565612794 -22.577235171974756,17.122792756958017 -22.572559173452948,17.09824518005372 -22.5226191338314,17.06502870361329 -22.528803166402827,17.03558877746583 -22.543548588275577))",
    srid: 4326,
  );

  $polygonData = $polygon->toArray();
  $polygonFromArray = Polygon::fromArray($polygonData);
  
  expect($polygonFromArray->srid)->toBe(4326); // fails
});
```

Can you find a workaround to overcome this issue?

**Comment by Krato** [comment]
Yeah, that's what I thought 

Maybe it's possible to add the srid to the array? So when converting again to the Polygon object keeps the srid?

On my project I just finished using the creating/updating event on model boot and overriding the srid. But this is just a quick fix.
