### ISSUE TITLE
Illuminate\Database\SQLiteConnection error

### ISSUE THREAD

**Issue by PankovAlxndr** [MatanYadaev/laravel-eloquent-spatial#89]
- Laravel: 10.5.0
- matanyadaev/laravel-eloquent-spatial: 3.1.2
- PHPUnit: 10.0.19
- Pest: 2

phpunit.xml
```
<server name="DB_CONNECTION" value="sqlite"/>
<server name="DB_DATABASE" value=":memory:"/>
```

I write a FeatureTest which creates a model through a factory, and the factory looks like this:
```
public function definition(): array
  {
      return [
          ...
          'address' => $this->faker->address(),
          'point' => new Point($this->faker->latitude, $this->faker->longitude),
          ...
      ];
  }
```
Inside my test, I execute the following code: `MyModel::factory()->create()` and I get the following error

Error:
`MatanYadaev\EloquentSpatial\AxisOrder::isMariaDb(): Argument #1 ($connection) must be of type Illuminate\Database\MySqlConnection, Illuminate\Database\SQLiteConnection given, called in /app/vendor/matanyadaev/laravel-eloquent-spatial/src/AxisOrder.php on line 18`

I can somehow make it work with sql-lite?

**Comment by MatanYadaev** [comment]
Hi @PankovAlxndr, this package doesn't support SQLite. It supports only MySQL at the moment.
It will require some refactoring to make this package support more than one DB.
I will be happy to accept a PR that introduces this functionality.
