### ISSUE TITLE
Connection Exception if run in Octane mode

### ISSUE THREAD

**Issue by sirvantos** [MatanYadaev/laravel-eloquent-spatial#91]
The bug appears after approximately 40 - 60 secs of instance lifetime, probably due connection outdating.... In regular FPM mode it is working as expected.

{
    "class": "Error",
    "message": "Call to a member function getAttribute() on null",
    "code": 0,
    "file": "/var/task/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:23",
    "trace": [
        "/var/task/vendor/matanyadaev/laravel-eloquent-spatial/src/AxisOrder.php:34",
        "/var/task/vendor/matanyadaev/laravel-eloquent-spatial/src/AxisOrder.php:18",
        "/var/task/vendor/matanyadaev/laravel-eloquent-spatial/src/Objects/Geometry.php:219",
        "/var/task/vendor/matanyadaev/laravel-eloquent-spatial/src/SpatialBuilder.php:326",
        "/var/task/vendor/matanyadaev/laravel-eloquent-spatial/src/SpatialBuilder.php:95",
        "/var/task/app/Domain/Car/Actions/GetChargingStations.php:111",
        "/var/task/vendor/laravel/framework/src/Illuminate/Conditionable/Traits/Conditionable.php:34",
        "/var/task/app/Domain/Car/Actions/GetChargingStations.php:114",
        "/var/task/app/Domain/Car/Actions/GetChargingStations.php:29",
        "/var/task/app/Domain/Car/Http/Controllers/Api/ChargingStationController.php:469",

**Comment by MatanYadaev** [comment]
Hi @sirvantos. I'm not using Octance so I'm not very sure how to fix it. Can you submit a PR?
