### ISSUE TITLE
Feature request: validation rules

### ISSUE THREAD

**Issue by aricooperdavis** [MatanYadaev/laravel-eloquent-spatial#92]
It would be quite nice to include [validation rules](https://laravel.com/docs/10.x/validation#custom-validation-rules) that could be used in form validations to validate appropriate JSON representations of each class.

For example, we could then validate requests using:

```php
use MatanYadaev\EloquentSpatial\Rules\Point;
 
$request->validate([
    'location' => ['required', new Point],
]);
```

rather than having to do it manually, such as:

```php
$request->validate([
    'location' => ['required', 'array:type,coordinates'],
    'location.type' => ['required', 'in:Point'],
    'location.coordinates' => ['required', 'array:0,1'],
    'location.coordinates.0' => ['required', 'numeric', 'min:-90', 'max:90'],
    'location.coordinates.1' => ['required', 'numeric', 'min:-180', 'max:180'],
]);
```

Unless I'm being a bit thick and can do it more easily than this?

**Comment by MatanYadaev** [comment]
Hi @aricooperdavis, sounds cool. Can you submit a PR?

**Comment by aricooperdavis** [comment]
Actually, perhaps this is out of scope for this package, as it's already implemented here: https://github.com/yucadoo/laravel-geojson-rule ?
