### ISSUE TITLE
Support Postgres

### ISSUE THREAD

**Issue by MatanYadaev** [MatanYadaev/laravel-eloquent-spatial#93]

**Comment by camohub** [comment]
Me too

**Comment by sekru1** [comment]
What are the plans to make this library Postgres-compatible? I could really use this for a project based on Laravel Nova.

**Comment by davidldear** [comment]
Our team could use the postgres support as well.  Happy to help but we might need a little direction.

**Comment by MatanYadaev** [comment]
Hi guys, I don't plan to implement the support for Postgres as I don't need it at the moment, but I will be happy to accept PRs.

**Comment by zartdinov** [comment]
It's not difficult to implement. I tested it locally a little, I’ll try to do it soon when I have some free time.

**Comment by zartdinov** [comment]
I'll try to prepare PR this weekend.

**Comment by zartdinov** [comment]
I started in my fork, first commit here (wthout tests yet):
https://github.com/zartdinov/laravel-eloquent-spatial/commit/44ab50922a41605f133f01707c61f1d31f719581

I am going to update workflow soon. Need some tests for different versions of postgres.

**Comment by MatanYadaev** [comment]
Can you guys please help me and review #109?

**Comment by zartdinov** [comment]
Code looks very nice for me.
Better than my try ;)

I think we can fix it later after some feedback from postgres users. For example, we are using postgis-15.3.3 for now.

Thank you. It was difficult to find time to configure and fix all existing workflow, sorry.
