### ISSUE TITLE
Compatibility Issue with SQLiteConnection when using PHPUnit

### ISSUE THREAD

**Issue by RizwanNaasir** [MatanYadaev/laravel-eloquent-spatial#94]
# Issue Description
When using with PHPUnit and the SQLiteConnection driver, I encountered a compatibility issue with the AxisOrder class. The issue arises due to the differences in SQL syntax between SQLite and other database systems.

# Steps to Reproduce
- Set up a Laravel project with the MatanYadaev/laravel-eloquent-spatial library.
- Configure the database connection to use the SQLiteConnection driver.
- Write test cases using PHPUnit that involve spatial data and the AxisOrder class.

# Expected Behavior
I expected the test cases to run successfully and pass, regardless of the database driver used.

# Actual Behavior
When running the test cases with the SQLiteConnection driver, I encountered errors related to the AxisOrder class. It seems that the SQL syntax used by the library is not compatible with SQLite, resulting in failed queries and test failures.

# Reproducible Example
Here is a simplified example of a failing test case:

```php
use PHPUnit\Framework\TestCase;
use MatanYadaev\EloquentSpatial\Types\Point;
use App\Models\Location;

class SpatialTest extends TestCase
{
    public function testSpatialQuery()
    {
        $location = new Location();
        $location->point = new Point(1, 2);
        $location->save();

        // Perform some spatial queries or assertions
        // ...

        $this->assertTrue(true);
    }
}
```
# Environment
Laravel version:  ^10
Laravel Eloquent Spatial version:^2.10
PHPUnit version: ^10.0
Database driver: SQLite

# Possible Solution
Possible fix in `Axis` class:

To address the compatibility issue between `MatanYadaev/laravel-eloquent-spatial` and `SQLiteConnection`, you can modify the `Axis` class as follows:

   ```php
   public static function fromWKT($wkt)
   {
       // ...

       // Add conditional check for SQLiteConnection
       if (app('db')->connection() instanceof \Illuminate\Database\SQLiteConnection) {
           // Handle SQLite-specific behavior here
           // For example, convert the WKT to a different format or implement a workaround
           // based on the limitations of SQLite's spatial support.
           // ...
       }
       
       // ...

       return $axis;
   }
   ```

- Inside the conditional block, you can implement specific logic or workarounds to handle the limitations of spatial support in SQLite. This could involve converting the WKT format or utilizing SQLite-specific functions.

-  Save the changes to the `Axis.php` file.

- Test your application to verify that the compatibility issue has been resolved .

# Additional Information
I have tested the same code with other database drivers (e.g., MySQL) and did not encounter any issues.
I have checked the documentation and GitHub repository of the MatanYadaev/laravel-eloquent-spatial library but did not find any specific information regarding SQLite compatibility.

**Comment by MatanYadaev** [comment]
Hi @RizwanNaasir, as you mentioned, this package doesn't support any DB except MySQL.
In order to support more DBs, a major refactor is required, and not just a small workaround, unfortunately.
I'll be happy to accept PRs!
