### ISSUE TITLE
why "geometry" type is not in `/src/Doctrine/` ?

### ISSUE THREAD

**Issue by well-place-dev2** [MatanYadaev/laravel-eloquent-spatial#98]
I want to use "geometry" type like `$table->geometry('location')`, but this is not supported because Geometry type declaration for doctrine/dbal is not in `/src/Doctrine`. How can I use "geometry" type?

**Comment by MatanYadaev** [comment]
Can you please rexplain what are you trying to achieve? I'm not sure I understand the issue. A branch with failing test will be ideal

**Comment by well-place-dev2** [comment]
Sorry for lack of expalanation.
I'm using `laravel-eloquent-spatial` with laravel9. When I create column of geometry type in mysql8, I received error message like below.

```
 public function up()
{
  Schema::table('addresses', function (Blueprint $table) {
    $table->geometry('location')->nullable()->comment('地点');
  });
}
```

```
Doctrine\DBAL\Exception : Unknown database type geometry requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.
```

I think It's because Geometry type declaration for doctrine/dbal is not in /src/Doctrine. Why is it not declared?

**Comment by MatanYadaev** [comment]
I wasn't able to reproduce this issue. Can you please fork this repo and add a failing test?
Anyway, geometry types migrations aren't related to this package, it's built-in Laravel.
